<?php

namespace BEGrA\UtilisateurBundle\Repository;

/**
 * TravaillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravaillerRepository extends \Doctrine\ORM\EntityRepository
{
}
