bureau_etude_adhesion_homepage:
    path:     /
    defaults: { _controller: BureauEtudeAdhesionBundle:Default:index }


bureau_etude_adhesion_test:
    path:     /test
    defaults: { _controller: BureauEtudeAdhesionBundle:Default:new }
