bureau_etude_adhesion_homepage:
    path:     /
    defaults: { _controller: BureauEtudeAdhesionBundle:Default:index }


bureau_etude_adhesion_enfant:
    path:     /enfant
    defaults: { _controller: BureauEtudeAdhesionBundle:Default:creerEnfant }

bureau_etude_adhesion_tuteur:
    path:     /tuteur
    defaults: { _controller: BureauEtudeAdhesionBundle:Default:creerTuteur }
