#----------------------------------------------------------------------------
#---------------------------------Enfant-------------------------------------
#----------------------------------------------------------------------------

bureau_etude_adhesion_enfant_vue:
    path:     /Enfant/vue/{id}
    defaults: { _controller: BureauEtudeAdhesionBundle:Enfant:vue }
    requirements:
      id: \d+

bureau_etude_adhesion_enfant_creer:
    path:     /Enfant/creer
    defaults: { _controller: BureauEtudeAdhesionBundle:Enfant:creer }

bureau_etude_adhesion_enfant_editer:
    path:     /Enfant/editer/{id}
    defaults: { _controller: BureauEtudeAdhesionBundle:Enfant:editer }
    requirements:
      id: \d+

bureau_etude_adhesion_enfant_supprimer:
    path:     /Enfant/supprimer/{id}
    defaults: { _controller: BureauEtudeAdhesionBundle:Enfant:supprimer }
    requirements:
      id: \d+

bureau_etude_adhesion_enfant_index:
    path:     /Enfant/{nb}
    defaults: { _controller: BureauEtudeAdhesionBundle:Enfant:index, nb: 1 }
    requirements:
      id: \d+

#----------------------------------------------------------------------------
#---------------------------------Tuteur-------------------------------------
#----------------------------------------------------------------------------

bureau_etude_adhesion_tuteur_vue:
    path:     /Tuteur/vue/{id}
    defaults: { _controller: BureauEtudeAdhesionBundle:Tuteur:vue }
    requirements:
      id: \d+

bureau_etude_adhesion_tuteur_creer:
    path:     /Tuteur/creer
    defaults: { _controller: BureauEtudeAdhesionBundle:Tuteur:creer }

bureau_etude_adhesion_tuteur_editer:
    path:     /Tuteur/editer/{id}
    defaults: { _controller: BureauEtudeAdhesionBundle:Tuteur:editer }
    requirements:
      id: \d+

bureau_etude_adhesion_tuteur_supprimer:
    path:     /Tuteur/supprimer/{id}
    defaults: { _controller: BureauEtudeAdhesionBundle:Tuteur:supprimer }
    requirements:
      id: \d+
      
bureau_etude_adhesion_tuteur_index:
    path:     /Tuteur/{nb}
    defaults: { _controller: BureauEtudeAdhesionBundle:Tuteur:index, nb: 1 }
    requirements:
      id: \d+