bureau_etude_core_homepage:
    path:     /
    defaults: { _controller: BureauEtudeCoreBundle:Default:index }

bouton_generation_liste:
    path:     /ListeProduits
    defaults: { _controller: BureauEtudeCoreBundle:Bouton:listeProduits }