<?php

namespace BEGrA\AdhesionBundle\Repository;

/**
 * AdhererRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdhererRepository extends \Doctrine\ORM\EntityRepository
{
}
