bureau_etude_core:
    resource: "@BureauEtudeCoreBundle/Resources/config/routing.yml"
    prefix:   /

bureau_etude_scolarite:
    resource: "@BureauEtudeScolariteBundle/Resources/config/routing.yml"
    prefix:   /Scolarite

bureau_etude_adhesion:
    resource: "@BureauEtudeAdhesionBundle/Resources/config/routing.yml"
    prefix:   /Adhesion