be_gr_a_operation:
    resource: "@BEGrAOperationBundle/Resources/config/routing.yml"
    prefix:   /

be_gr_a_utilisateur:
    resource: "@BEGrAUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

be_gr_a_adhesion:
    resource: "@BEGrAAdhesionBundle/Resources/config/routing.yml"
    prefix:   /

be_gr_a_scolarite:
    resource: "@BEGrAScolariteBundle/Resources/config/routing.yml"
    prefix:   /

be_gr_a_produit:
    resource: "@BEGrAProduitBundle/Resources/config/routing.yml"
    prefix:   /

be_gr_a_core:
    resource: "@BEGrACoreBundle/Resources/config/routing.yml"
    prefix:   /
