<?php

namespace BEGrA\ScolariteBundle\Repository;

/**
 * ListerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListerRepository extends \Doctrine\ORM\EntityRepository
{
}
